[package]
name = "smt2020"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
des-core = { path = "../des-core" }
libm = "0.2"
postcard = { version = "1", default-features = false, features = ["alloc"] }
rand_xoshiro = "0.8"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
